services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  frenemies:
    container_name: frenemies
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my_network
    environment:
      DOCKER_COMPOSE: true

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge
